import type { ChatScenario, ScenarioMessage } from './scenarios';

const scenarioHistory: Record<string, ScenarioMessage[]> = {
  'Friday rescue mission': [
    { text: "made it home. thanks for keeping dinner warm", isOwn: false },
    { text: "you owe me one very specific bowl of ramen", isOwn: true },
    { text: "already knew that was coming", isOwn: false },
    { text: "good. same place next friday", isOwn: true },
  ],
  'The usual brunch': [
    { text: "your basil plant is still alive somehow", isOwn: false },
    { text: "because i left you a three-page care guide", isOwn: true },
    { text: "i used it as a coaster but remembered the sunny window part", isOwn: false },
    { text: "i'm taking the plant back this weekend", isOwn: true },
  ],
  'Sibling grocery duty': [
    { text: "dad says the oat milk tastes different", isOwn: false },
    { text: "you bought vanilla again, didn't you", isOwn: true },
    { text: "the cartons look identical", isOwn: false },
    { text: "they really do not", isOwn: true },
  ],
  'Design partner feedback': [
    { text: "client liked the onboarding changes", isOwn: false },
    { text: "even the progress bar they wanted removed?", isOwn: true },
    { text: "especially that. we are never mentioning this again", isOwn: false },
    { text: "screenshot saved for future arguments", isOwn: true },
  ],
  'Apartment key': [
    { text: "luna finally stopped sitting on my suitcase", isOwn: false },
    { text: "she knows that suitcase means you're leaving", isOwn: true },
    { text: "i bribed her with the treats you brought", isOwn: false },
    { text: "those were supposed to last all week", isOwn: true },
  ],
  'Book club rivalry': [
    { text: "i still think the neighbor did it", isOwn: false },
    { text: "you suspect every neighbor in every mystery", isOwn: true },
    { text: "one day i'll be right", isOwn: false },
    { text: "not in this book", isOwn: true },
  ],
  'Running accountability': [
    { text: "my legs have filed a complaint after that hill", isOwn: true },
    { text: "you said you wanted a harder route", isOwn: false },
    { text: "i was feeling optimistic at the time", isOwn: true },
    { text: "recovery coffee tomorrow. no running", isOwn: false },
  ],
  'Cousin wedding photos': [
    { text: "mom printed the blurry dance photo", isOwn: false },
    { text: "the one i told her not to print?", isOwn: true },
    { text: "framed it and put it in the hallway", isOwn: false },
    { text: "we can never visit again", isOwn: true },
  ],
  'Neighbor plant care': [
    { text: "fernando has a new leaf", isOwn: false },
    { text: "send a photo immediately", isOwn: true },
    { text: "you are more excited about this than my promotion", isOwn: false },
    { text: "i sent flowers for the promotion. this is different", isOwn: true },
  ],
  'Shared playlist dispute': [
    { text: "the road trip playlist is six hours now", isOwn: false },
    { text: "perfect, the drive is five and a half", isOwn: true },
    { text: "you added the live version and studio version of the same song", isOwn: false },
    { text: "they have completely different energy", isOwn: true },
  ],
  'Co-op game night': [
    { text: "saved the last replay. your heroic rescue is preserved", isOwn: false },
    { text: "i remember you hiding behind a crate", isOwn: true },
    { text: "tactical cover", isOwn: false },
    { text: "sure. tactical screaming too", isOwn: true },
  ],
  'Family recipe': [
    { text: "grandma finally admitted she changes the recipe every time", isOwn: false },
    { text: "that explains why our notes never work", isOwn: true },
    { text: "she said measuring spoons ruin the fun", isOwn: false },
    { text: "honestly that sounds like her", isOwn: true },
  ],
  'Airport callback': [
    { text: "boarding now. i remembered the charger", isOwn: false },
    { text: "and your passport?", isOwn: true },
    { text: "checked three times because of you", isOwn: false },
    { text: "my work here is done", isOwn: true },
  ],
  'Old roommate mail': [
    { text: "your plant mail somehow arrived here too", isOwn: false },
    { text: "plant mail?", isOwn: true },
    { text: "a catalog with twelve pages of ceramic pots", isOwn: false },
    { text: "keep that one. i'm coming by sunday", isOwn: true },
  ],
  'Dinner at home': [
    { text: "Kal jo rajma pack kiya tha office le gaye the?", isOwn: false },
    { text: "Haan, Rohan ne aadha kha liya aur recipe bhi maangi", isOwn: true },
    { text: "Usko bolna Sunday ko aa jaye, fresh bana dungi", isOwn: false },
    { text: "Bol diya. Ab woh mujhe daily reminder bhej raha hai", isOwn: true },
  ],
  'Metro besties': [
    { text: "Kal ki photos bhej na, especially woh bookstore wali", isOwn: false },
    { text: "Album mein daal di. Tune phir aankhein band kar li ek photo mein", isOwn: true },
    { text: "Tradition hai. Har outing mein ek aisi photo zaroori hai", isOwn: false },
    { text: "Usi ko contact photo bana raha hoon", isOwn: true },
  ],
  'College notes trade': [
    { text: "Lab file submit ho gayi ya phir last minute karega?", isOwn: false },
    { text: "Cover page tak ho gaya. Progress bolte hain isko", isOwn: true },
    { text: "Pichli baar bhi cover page dikha ke khush tha", isOwn: false },
    { text: "Aur pass bhi ho gaya tha", isOwn: true },
  ],
  'Sibling shaadi shopping': [
    { text: "Blue kurta dry clean se aa gaya. Is baar time pe", isOwn: false },
    { text: "Miracle. Last function mein safety pin se kaam chala tha", isOwn: true },
    { text: "Please woh photo family group mein mat bhejna", isOwn: false },
    { text: "Already saved in favourites", isOwn: true },
  ],
  'Office chai break': [
    { text: "Kal ke client notes dekhe? Point 6 samajh aaya?", isOwn: false },
    { text: "Nahi. Shreya ko bhi nahi aaya, so we're safe", isOwn: true },
    { text: "Maine follow-up mail daal diya. Ab dekhte hain", isOwn: false },
    { text: "Brave. Chai meri taraf se", isOwn: true },
  ],
  'Monsoon pickup': [
    { text: "Tera umbrella meri car mein mil gaya", isOwn: true },
    { text: "Oh, isliye poore hafte cupboard mein dhoondh rahi thi", isOwn: false },
    { text: "Wahi yellow wala jo tu kabhi carry nahi karti", isOwn: true },
    { text: "Carry karti hoon, bas ghar wapas nahi laati", isOwn: false },
  ],
  'Cricket superstition': [
    { text: "Last match ki jersey wash kar di kya?", isOwn: false },
    { text: "Haan, normal log kapde wash karte hain", isOwn: true },
    { text: "Us jersey mein hum teen match jeete the", isOwn: false },
    { text: "Team jeeti thi, meri laundry nahi", isOwn: true },
  ],
  'Society parking saga': [
    { text: "Lift ka issue finally solve hua?", isOwn: true },
    { text: "Haan, but group mein ab water tanker ka naya debate hai", isOwn: false },
    { text: "Mute kar de. Pichle Sunday ka lesson bhool gaya?", isOwn: true },
    { text: "Mute kiya tha, secretary ne direct call kar diya", isOwn: false },
  ],
  'Train trip planning': [
    { text: "Pondicherry trip ka expense sheet finally close kiya", isOwn: false },
    { text: "Mere 280 rupees abhi bhi pending dikha raha hai", isOwn: true },
    { text: "Because tune dosa ko transport category mein daala tha", isOwn: false },
    { text: "It travelled from kitchen to our table", isOwn: true },
  ],
  'Dadi video call': [
    { text: "Dadi ne phir good morning photo sirf mujhe bheja", isOwn: false },
    { text: "Forward kar de, mera collection incomplete hai", isOwn: true },
    { text: "Aaj wala sunrise plus twelve roses hai", isOwn: false },
    { text: "Premium edition. Save kar raha hoon", isOwn: true },
  ],
  'Flatmate tiffin mystery': [
    { text: "Gas cylinder book kar diya tha na?", isOwn: false },
    { text: "Haan, Saturday delivery. OTP tujhe aayega", isOwn: true },
    { text: "Last time tu meeting mein tha aur delivery wala chala gaya", isOwn: false },
    { text: "Is baar reminder, alarm, sab laga diya", isOwn: true },
  ],
  'Dad and the router': [
    { text: "Tumne photos TV pe kaise chalayi thi pichli baar?", isOwn: false },
    { text: "Papa, gallery mein cast button tha. Kal aake phir dikha dunga", isOwn: true },
    { text: "Likha tha maine, par paper mil nahi raha", isOwn: false },
    { text: "Is baar note phone mein save karwa dunga", isOwn: true },
  ],
  'School friend reunion': [
    { text: "Aaj Purani Dilli wali photo mili, class picnic ki", isOwn: false },
    { text: "Please bol ki woh cap wali nahi hai", isOwn: true },
    { text: "Exactly wohi. Tu khud ko rapper samajhta tha", isOwn: false },
    { text: "We were fourteen. Evidence destroy kar", isOwn: true },
  ],
  'Diwali light repair': [
    { text: "Pichle saal wali rangoli stencils mil gayi", isOwn: false },
    { text: "Good, freehand pe trust nahi hai mujhe after last time", isOwn: true },
    { text: "Last time diya gir gaya tha, design theek tha", isOwn: false },
    { text: "Mummy still calls it abstract art", isOwn: true },
  ],
};

const globalBaseScenarios: ChatScenario[] = [
  {
    name: 'Friday rescue mission',
    contactName: 'Liam Carter',
    messages: [
      { text: "your favorite manager just dropped three tasks on me at 4:55", isOwn: false },
      { text: "again? he did the exact same thing before your birthday dinner", isOwn: true },
      { text: "YES and called them quick wins 😭", isOwn: false },
      { text: "close the laptop. you already covered for him twice this week", isOwn: true },
      { text: "you’re a terrible influence", isOwn: false },
      { text: "i’m the reason you still have weekends", isOwn: true },
      { text: "fair. ramen at our usual place in twenty?", isOwn: false },
      { text: "already leaving", isOwn: true },
    ],
  },
  {
    name: 'The usual brunch',
    contactName: 'Maya Chen',
    messages: [
      { text: "please tell me you remembered to book our table", isOwn: false },
      { text: "of course. window seat, 11:30, extra hash browns", isOwn: true },
      { text: "this is why you’ve been my favorite person since freshman year", isOwn: false },
      { text: "last month you said that because i carried your plant upstairs", isOwn: true },
      { text: "both things can be true", isOwn: false },
      { text: "are you bringing the camera?", isOwn: true },
      { text: "yes, and i charged it this time. character growth", isOwn: false },
    ],
  },
  {
    name: 'Sibling grocery duty',
    contactName: 'Noah Williams',
    messages: [
      { text: "mom sent me the grocery list and somehow it has 43 things", isOwn: false },
      { text: "because you said ‘leave it to me’ in the family chat", isOwn: true },
      { text: "i was trying to sound responsible", isOwn: false },
      { text: "rookie mistake. send me half the list", isOwn: true },
      { text: "you get vegetables and the weird oat milk dad likes", isOwn: false },
      { text: "fine, but you’re carrying everything upstairs", isOwn: true },
      { text: "deal. same supermarket as usual?", isOwn: false },
      { text: "yep, meet by the bakery in ten", isOwn: true },
    ],
  },
  {
    name: 'Design partner feedback',
    contactName: 'Sofia Martinez',
    messages: [
      { text: "i fixed the pricing screen you roasted yesterday", isOwn: false },
      { text: "reviewed, not roasted. there was constructive affection", isOwn: true },
      { text: "you wrote ‘why is this button hiding from its responsibilities’", isOwn: false },
      { text: "and now it’s visible. my methods work", isOwn: true },
      { text: "annoyingly, yes. want the new link?", isOwn: false },
      { text: "send it. i’ll check before our 3 pm", isOwn: true },
      { text: "thank you. coffee is on me after the review", isOwn: false },
    ],
  },
  {
    name: 'Apartment key',
    contactName: 'Daniel Kim',
    messages: [
      { text: "did you take my spare key after feeding luna?", isOwn: false },
      { text: "check the blue bowl by your door", isOwn: true },
      { text: "found it. i checked that bowl twice somehow", isOwn: false },
      { text: "same way you missed your passport on the kitchen table", isOwn: true },
      { text: "we agreed never to mention airport morning again", isOwn: false },
      { text: "i agreed to keep reminding you forever", isOwn: true },
      { text: "rude. luna misses you though", isOwn: false },
      { text: "tell her i’ll visit this weekend", isOwn: true },
    ],
  },
  {
    name: 'Book club rivalry',
    contactName: 'Ava Thompson',
    messages: [
      { text: "finished the book. your theory was completely wrong", isOwn: false },
      { text: "you promised not to gloat until book club", isOwn: true },
      { text: "i waited six whole minutes before texting you", isOwn: false },
      { text: "impressive restraint", isOwn: true },
      { text: "chapter twelve made it painfully obvious", isOwn: false },
      { text: "says the person who accused the librarian", isOwn: true },
      { text: "she was suspicious! anyway, drinks at seven as usual?", isOwn: false },
      { text: "seven works. bring the book this time", isOwn: true },
    ],
  },
  {
    name: 'Running accountability',
    contactName: 'Marcus Reed',
    messages: [
      { text: "outside your building. don’t pretend you’re asleep", isOwn: false },
      { text: "it is six in the morning, i am spiritually asleep", isOwn: true },
      { text: "you made me sign up for this race", isOwn: false },
      { text: "past me was overly confident", isOwn: true },
      { text: "shoes on. easy 5k, same river route", isOwn: false },
      { text: "your easy pace nearly ended me on tuesday", isOwn: true },
      { text: "i brought the good coffee for after", isOwn: false },
      { text: "coming down", isOwn: true },
    ],
  },
  {
    name: 'Cousin wedding photos',
    contactName: 'Elena Rossi',
    messages: [
      { text: "aunt maria is asking for the wedding photos again", isOwn: false },
      { text: "i sent her the album yesterday", isOwn: true },
      { text: "she wants the one where grandpa is dancing on the chair", isOwn: false },
      { text: "obviously. that’s the family’s new historical document", isOwn: true },
      { text: "send it to me too, i need a new contact photo for him", isOwn: false },
      { text: "you’re going to get us removed from the group chat", isOwn: true },
      { text: "worth it", isOwn: false },
    ],
  },
  {
    name: 'Neighbor plant care',
    contactName: 'Chloe Anderson',
    messages: [
      { text: "your dramatic fern survived the weekend", isOwn: false },
      { text: "did you use the tiny watering cup like i showed you?", isOwn: true },
      { text: "yes, professor plant. exactly half a cup", isOwn: false },
      { text: "mock me all you want, fernando is sensitive", isOwn: true },
      { text: "fernando also dropped dirt all over my windowsill", isOwn: false },
      { text: "i’ll clean it when i pick him up tonight", isOwn: true },
      { text: "bring those lemon cookies and we’re even", isOwn: false },
    ],
  },
  {
    name: 'Shared playlist dispute',
    contactName: 'Theo Morgan',
    messages: [
      { text: "who added six sad acoustic songs to the road trip playlist", isOwn: false },
      { text: "you played the same dance track four times last trip", isOwn: true },
      { text: "because it kept morale alive", isOwn: false },
      { text: "we were stuck in traffic for three hours", isOwn: true },
      { text: "exactly. we needed consistency", isOwn: false },
      { text: "i’ll remove two sad songs if you remove two remixes", isOwn: true },
      { text: "painful, but fair", isOwn: false },
    ],
  },
  {
    name: 'Co-op game night',
    contactName: 'Jake Miller',
    messages: [
      { text: "we’re not telling the others you pushed me off the map again", isOwn: false },
      { text: "you walked directly in front of me", isOwn: true },
      { text: "after four years of playing together, you know i do that", isOwn: false },
      { text: "that is not the defense you think it is", isOwn: true },
      { text: "rematch tonight? same squad at nine", isOwn: false },
      { text: "only if you stop looting while i’m being attacked", isOwn: true },
      { text: "no promises, but i’ll try", isOwn: false },
    ],
  },
  {
    name: 'Family recipe',
    contactName: 'Olivia Parker',
    messages: [
      { text: "grandma’s soup tastes wrong and she won’t tell me what i missed", isOwn: false },
      { text: "did you brown the onions first? you skipped that last christmas", isOwn: true },
      { text: "i did! and i used the old green pot", isOwn: false },
      { text: "then it needs the tiny spoon of mustard", isOwn: true },
      { text: "there is mustard in this??", isOwn: false },
      { text: "apparently that was a family secret until today", isOwn: true },
      { text: "trying it now. if this works, you’re getting first bowl", isOwn: false },
    ],
  },
  {
    name: 'Airport callback',
    contactName: 'Emma Wilson',
    messages: [
      { text: "landed early. please say you’re not at the wrong terminal again", isOwn: false },
      { text: "that happened once and the signs were confusing", isOwn: true },
      { text: "you sent me a photo from departures", isOwn: false },
      { text: "today i am confidently at arrivals, door four", isOwn: true },
      { text: "good. baggage claim is slow anyway", isOwn: false },
      { text: "i brought your usual coffee", isOwn: true },
      { text: "all is forgiven", isOwn: false },
    ],
  },
  {
    name: 'Old roommate mail',
    contactName: 'Lucas Martin',
    messages: [
      { text: "another letter for you showed up at the old apartment", isOwn: false },
      { text: "please don’t say it’s from the gym i cancelled three times", isOwn: true },
      { text: "worse. it says ‘we miss you’ in giant letters", isOwn: false },
      { text: "they miss my monthly payment", isOwn: true },
      { text: "i’ll leave it with the doorman like last time", isOwn: false },
      { text: "thanks. dinner on me next week for becoming my mail service", isOwn: true },
      { text: "i’m ordering dessert too", isOwn: false },
    ],
  },
];

export const globalScenarios: ChatScenario[] = globalBaseScenarios.map((scenario) => ({
  ...scenario,
  messages: [...(scenarioHistory[scenario.name] ?? []), ...scenario.messages],
}));

const indianBaseScenarios: ChatScenario[] = [
  {
    name: 'Dinner at home',
    contactName: 'Mom',
    messages: [
      { text: "Aaj bhi late meeting hai kya? Kal jaisa dinner thanda mat karwana", isOwn: false },
      { text: "Nahi, aaj 7:15 tak nikal jaunga pakka", isOwn: true },
      { text: "Pakka wala pakka ya tumhara office wala pakka?", isOwn: false },
      { text: "Mummy 😭 actual pakka. Nikalte hi call karunga", isOwn: true },
      { text: "Theek hai. Raste se doodh le aana, wahi blue packet", isOwn: false },
      { text: "Haan yaad hai, last time green le aaya tha", isOwn: true },
      { text: "Isliye reminder diya. Jaldi aana 🙂", isOwn: false },
    ],
  },
  {
    name: 'Metro besties',
    contactName: 'Priya Sharma',
    messages: [
      { text: "Rajiv Chowk aa gayi. Tu phir galat gate pe toh nahi hai?", isOwn: false },
      { text: "Gate 3. Pichli baar ek hi baar galti hui thi", isOwn: true },
      { text: "Ek baar? CP ke teen chakkar lagwaye the", isOwn: false },
      { text: "Aaj compensation mein cold coffee la raha hoon", isOwn: true },
      { text: "Without sugar, warna dosti khatam", isOwn: false },
      { text: "Already ordered. Five minutes", isOwn: true },
      { text: "Good. Main bookshop ke bahar hoon", isOwn: false },
    ],
  },
  {
    name: 'College notes trade',
    contactName: 'Aarav Patel',
    messages: [
      { text: "Bhai kal ke notes bhej de, proxy lagane ka full payment", isOwn: false },
      { text: "Tu meri proxy mein present bolna bhool gaya tha", isOwn: true },
      { text: "Sir ne naam itni jaldi bola 😭 next class pakka", isOwn: false },
      { text: "Fine. Chapter 4 ke notes bhej raha hoon", isOwn: true },
      { text: "Legend. Canteen wali chai meri taraf se", isOwn: false },
      { text: "Chai plus samosa. Interest lagega", isOwn: true },
      { text: "Loot macha rakhi hai, but done", isOwn: false },
    ],
  },
  {
    name: 'Sibling shaadi shopping',
    contactName: 'Ananya Rao',
    messages: [
      { text: "Mummy ne phir se gold kurta bheja hai family group mein", isOwn: false },
      { text: "Please bol de main dulha nahi hoon", isOwn: true },
      { text: "Maine bola. Unhone kaha ‘photo mein achha lagega’", isOwn: false },
      { text: "Yahi line last wedding pe bhi boli thi", isOwn: true },
      { text: "Sunday ko market chalte hain. Main choose karwa dungi", isOwn: false },
      { text: "Tera chosen floral shirt abhi tak yaad hai", isOwn: true },
      { text: "That shirt was iconic. 11 baje ready rehna", isOwn: false },
    ],
  },
  {
    name: 'Office chai break',
    contactName: 'Rohan Mehta',
    messages: [
      { text: "Client ne phir ‘small change’ bola hai", isOwn: false },
      { text: "Small change matlab poora dashboard naya?", isOwn: true },
      { text: "Exactly. Tum unko bahut achhe se samajh gaye ho", isOwn: false },
      { text: "Neeche chai? Warna main reply mein kuch honest likh dunga", isOwn: true },
      { text: "Five minutes. Same tapri", isOwn: false },
      { text: "Adrak wali order kar dena", isOwn: true },
      { text: "Already did. Tumhara mood predictable hai", isOwn: false },
    ],
  },
  {
    name: 'Monsoon pickup',
    contactName: 'Meera Iyer',
    messages: [
      { text: "Baarish full start ho gayi and obviously umbrella ghar pe hai", isOwn: false },
      { text: "Obviously. Last monsoon ke baad bhi nahi seekha", isOwn: true },
      { text: "Lecture baad mein. Pick kar sakta hai?", isOwn: false },
      { text: "Haan, twenty minutes. Office ke main gate pe rehna", isOwn: true },
      { text: "Side gate better hai, wahan paani kam bharta hai", isOwn: false },
      { text: "Good point. Masala chai bhi le aaun?", isOwn: true },
      { text: "Isi liye tu favorite cousin hai", isOwn: false },
    ],
  },
  {
    name: 'Cricket superstition',
    contactName: 'Kabir Singh',
    messages: [
      { text: "TV se uthna mat. Jab se tu baitha hai wicket nahi gaya", isOwn: false },
      { text: "Mujhe washroom jaana hai bhai", isOwn: true },
      { text: "Drinks break tak control. Desh ka sawaal hai", isOwn: false },
      { text: "Last match bhi tune mujhe sofa pe hostage banaya tha", isOwn: true },
      { text: "Aur hum jeete the. Data supports me", isOwn: false },
      { text: "Fine. But next over mein snacks tu layega", isOwn: true },
      { text: "Deal. Bas position mat change karna", isOwn: false },
    ],
  },
  {
    name: 'Society parking saga',
    contactName: 'Vikram Sethi',
    messages: [
      { text: "Sharma uncle ne phir meri parking mein scooter laga diya", isOwn: false },
      { text: "Wahi blue scooter jo har weekend migrate karta hai?", isOwn: true },
      { text: "Haan. Ab watchman bol raha hai uncle nap le rahe hain", isOwn: false },
      { text: "Group mein photo mat daalna, pichli baar 87 messages aaye the", isOwn: true },
      { text: "I know. Secretary ne mujhe call karke lecture diya tha", isOwn: false },
      { text: "Key security pe chhod de. Main uncle ko evening walk pe pakadta hoon", isOwn: true },
      { text: "Hero. Chai meri taraf se", isOwn: false },
    ],
  },
  {
    name: 'Train trip planning',
    contactName: 'Kavya Nair',
    messages: [
      { text: "Friday wali train open hai. Is baar booking mujhe karne de", isOwn: false },
      { text: "Goa trip mein hum opposite coaches mein the because of you", isOwn: true },
      { text: "Website ne seats change ki thi, meri galti nahi", isOwn: false },
      { text: "You selected ‘any berth’ for six people", isOwn: true },
      { text: "Fine, screen share karke book karungi. Happy?", isOwn: false },
      { text: "Very. Evening 7:10 wali lete hain", isOwn: true },
      { text: "Done. ID details same hain na?", isOwn: false },
    ],
  },
  {
    name: 'Dadi video call',
    contactName: 'Tara Desai',
    messages: [
      { text: "Dadi ka video call set kar diya? Sunday ko phir ceiling hi dikh rahi thi", isOwn: false },
      { text: "Phone stand order kiya hai. Kal deliver hoga", isOwn: true },
      { text: "Good. Aur front camera ka sticker nikal dena", isOwn: false },
      { text: "Wait, sticker abhi tak laga hai?", isOwn: true },
      { text: "Haan, isliye hum sab soft focus mein dikhte hain", isOwn: false },
      { text: "Mystery solved after eight months", isOwn: true },
      { text: "Family tech support award tumhara", isOwn: false },
    ],
  },
  {
    name: 'Flatmate tiffin mystery',
    contactName: 'Neha Joshi',
    messages: [
      { text: "Mera steel tiffin phir tere bag mein hai kya?", isOwn: false },
      { text: "Check kar raha hoon. Mere paas teen kaise ho gaye?", isOwn: true },
      { text: "Because you collect them like Pokémon", isOwn: false },
      { text: "Blue lid wala tera hai na?", isOwn: true },
      { text: "Haan, and red lid Riya ka. Usko bhi do hafte se chahiye", isOwn: false },
      { text: "Tonight tiffin return ceremony karte hain", isOwn: true },
      { text: "Perfect. Dinner bhi tu bana raha hai as penalty", isOwn: false },
    ],
  },
  {
    name: 'Dad and the router',
    contactName: 'Dad',
    messages: [
      { text: "WiFi phir slow hai. Tumne last time jo kiya tha woh batao", isOwn: false },
      { text: "Router ke peeche black switch off karke ten seconds wait karo", isOwn: true },
      { text: "Black switch se TV toh band nahi hoga?", isOwn: false },
      { text: "Nahi papa, TV alag plug mein hai. Video call kar loon?", isOwn: true },
      { text: "Pehle try karta hoon. Tum har baar video call bol dete ho", isOwn: false },
      { text: "Because last time printer restart kar diya tha 😄", isOwn: true },
      { text: "Ab chal gaya. Printer wali baat mummy ko mat batana", isOwn: false },
    ],
  },
  {
    name: 'School friend reunion',
    contactName: 'Rahul Verma',
    messages: [
      { text: "School group finally reunion date decide kar raha hai", isOwn: false },
      { text: "Let me guess, fifteen people and twenty different dates", isOwn: true },
      { text: "Exactly. Saurabh ne spreadsheet bana diya", isOwn: false },
      { text: "Of course he did. Class monitor energy never leaves", isOwn: true },
      { text: "Tu 14th free hai? Main tere bina nahi jaa raha", isOwn: false },
      { text: "Free hoon. But old haircut photos koi nahi layega", isOwn: true },
      { text: "Too late, I already found the album", isOwn: false },
    ],
  },
  {
    name: 'Diwali light repair',
    contactName: 'Diya Shah',
    messages: [
      { text: "Balcony lights ka half section phir band hai", isOwn: false },
      { text: "Wahi set jo papa ne last year ‘perfectly fix’ kiya tha?", isOwn: true },
      { text: "Please unke saamne mat bolna. Already tools nikal liye hain", isOwn: false },
      { text: "Main spare lights leke aa raha hoon", isOwn: true },
      { text: "And extension board. Pichli baar humne fridge unplug kar diya tha", isOwn: false },
      { text: "That was your idea", isOwn: true },
      { text: "Family history will remember it differently", isOwn: false },
    ],
  },
];

export const indianScenarios: ChatScenario[] = indianBaseScenarios.map((scenario) => ({
  ...scenario,
  messages: [...(scenarioHistory[scenario.name] ?? []), ...scenario.messages],
}));
